name: PR Rebase
on:
  pull_request_review:
    types: [created]
jobs:
  autosquash:
    if: github.event.state == 'APPROVED' || github.event.body == '/rebase'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: samholmes/rebase@autosquash
        with:
          autosquash: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}